export const categoriesType = {
  CATEGORIES_LOAD: 'CATEGORIES_LOAD',
  CATEGORIES_LOAD_ERRORS: 'CATEGORIES_LOAD_ERRORS',
};
export const optionsTypes = {
  CHANGE_NAME: 'CHANGE_NAME',
  CHANGE_CATEGORY: 'CHANGE_CATEGORY',
  CHANGE_DIFFICULTY: 'CHANGE_DIFFICULTY',
  CHANGE_TYPE: 'CHANGE_TYPE',
  CHANGE_AMOUNT: 'CHANGE_AMOUNT',
  CLEAR_OPTIONS: 'CLEAR_OPTIONS',
};

export const questionsTypes = {
  QUESTIONS_LOAD: 'QUESTIONS_LOAD',
  QUESTIONS_LOAD_ERRORS: 'QUESTIONS_LOAD_ERRORS',
};
export const scoreAndIndexTypes = {
  SET_INDEX: 'SET_INDEX',
  SET_SCORE: 'SET_SCORE',
  CLEAR_SCORE_AND_INDEX: 'CLEAR_SCORE_AND_INDEX',
};
export const helpersTypes = {
  SET_MARKED_ANSWER: 'SET_MARKED_ANSWER',
  SET_ANSWER_SELECTED: 'SET_ANSWER_SELECTED',
};
export const rankTypes = {
  ADD_TO_RANK: 'ADD_TO_RANK',
};
