export const categoriesType = {
  CATEGORIES_LOAD: 'CATEGORIES_LOAD',
  CATEGORIES_LOAD_ERRORS: 'CATEGORIES_LOAD_ERRORS',
};
export const optionsTypes = {
  CHANGE_NAME: 'CHANGE_NAME',
  CHANGE_CATEGORY: 'CHANGE_CATEGORY',
  CHANGE_DIFFICULTY: 'CHANGE_DIFFICULTY',
  CHANGE_TYPE: 'CHANGE_TYPE',
  CHANGE_AMOUNT: 'CHANGE_AMOUNT',
};

export const questionsTypes = {
  QUESTIONS_LOAD: 'QUESTIONS_LOAD',
  QUESTIONS_LOAD_ERRORS: 'QUESTIONS_LOAD_ERRORS',
};
export const scoreAndIndexTypes = {
  SET_INDEX: 'SET_INDEX',
  SET_SCORE: 'SET_SCORE',
};
